import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextTopLoader from 'nextjs-toploader';
import "./globals.css";
import Link from 'next/link';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 function Navbar() {
  return (
    <center className="mt-5 mb-10">
      <Link href="/">Home</Link> &nbsp; | &nbsp;&nbsp;
      <Link href="/about">About</Link> &nbsp; | &nbsp;&nbsp;
      <Link href="/blog">Blog</Link>
    </center>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader 
          shadow="0 0 10px #2299DD,0 0 5px #2299DD" 
          showSpinner={false}
          height={2}/>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
